name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore --configfile NuGet.config
      - name: Build
        run: dotnet build --no-restore
      - name: Test JSON
        run: dotnet test BoBo.JSON.Tests/BoBo.JSON.Tests.csproj --no-build --verbosity normal
      - name: Test XML
        run: dotnet test BoBo.XML.Tests/BoBo.XML.Tests.csproj --no-build --verbosity normal
      - name: Test ASP.NET Core end-to-end
        run: dotnet test BoBo.ASPNETCore.Tests/BoBo.ASPNETCore.Tests.csproj --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack -c Release --configfile NuGet.config
      - name: Publish
        run: dotnet nuget push **/*.nupkg --configfile NuGet.config --source nuget.org --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
